enum RobotSequence {
    START,
    FOLLOW_LINE_TO_TARGET,
    PICKUP,
    BACKUP_FROM_TARGET,
	ROTATE_TO_SAFEZONE,
    OFF_TRACK_TO_SAFEZONE_DRIVE,
    DROPOFF,
    BACKUP_FROM_SAFEZONE,
    RETURN_TO_TRACK,
    FOLLOW_LINE_TO_START,
    END,
};
